Dockerfile

A Dockerfile is a text file containing instructions used to build a Docker image.

Common Instructions:

FROM
COPY
RUN
WORKDIR
CMD

Docker reads the Dockerfile and creates an image automatically.